URLS = [
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Project+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Project+Coordinator+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Director+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Construction+Project+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Senior+Project+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Project+Engineer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Program+Analyst+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Associate+Project+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Implementation+Specialist+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=construction+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=project+management+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=it+project+manager+%22series+c%22&l=Miami, FL&radius=25',
]