URLS = [
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+b%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+c%22&l=New York, NY&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+b%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+c%22&l=San Francisco, CA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+b%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+c%22&l=Boston, MA&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+b%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+c%22&l=Washington, DC&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Software+Engineer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Front+End+Developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Full+Stack+Developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Quality+Assurance+Engineer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Product+Manager+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Web+Developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Software+Architect+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Application+Developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=Development+Operations+Engineer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=software+developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=java+developer+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=java+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=computer+science+%22series+c%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+b%22&l=Miami, FL&radius=25',
			'https://www.indeed.com/jobs?q=devops+engineer+%22series+c%22&l=Miami, FL&radius=25',
]